#ifndef CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_EXPORT_H
#define CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_EXPORT_H

#include <QtCore/QtGlobal>

#if defined(MAKE_CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_LIB)
#  define CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_EXPORT_DECL Q_DECL_EXPORT
#else
#  define CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_EXPORT_DECL Q_DECL_IMPORT
#endif

#endif // CONTINENTALLANDSCAPEEVOLUTIONMODELPLUGIN_EXPORT_H


